print('                                    UNIVERSITY OF SINDH                         ')
print('                                        MARK SHEET                                   ')

print()

print('                                                                        SEAT NO:      2K20-CSE-107')
print('                                                                        DEPARTMENT:   CS')

print('Name: Mehdi Rizvi')
print('Father Name: Passand Ali')
print('Institute: Sindh University')

print()
print()

print('          S.NO              [Subject      |      Marks      |      Grade]                            ')

print()

mark1=['Python            ',60,'              B']
mark2=['Java              ',40,'              C']
mark3=['C++               ',80,'              A']
mark4=['English           ',75,'              B']
mark5=['Islamiyat         ',90,'              A']

totalmarks=mark1[1]+mark2[1]+mark3[1]+mark4[1]+mark5[1]

print(f'            1               {mark1}')
print(f'            2               {mark2}')
print(f'            3               {mark3}')
print(f'            4               {mark4}')
print(f'            5               {mark5}')

print()
print()

print('TOTAL MARKS:     'f'{totalmarks}')
print('RESULT:          Pass')